### ISSUE TITLE
Only 2 things I noticed in command line

### ISSUE THREAD

**Issue by HeidrHH** [Teskann/razer-waver#3]
Hello :)

and thank you for your work. 

The command line for my Razer BlackWidow V4 is the following:

`python3 create-wave.py -d 5 -D LR --fps 24 -c 23 -r 8 --device "Razer BlackWidow V4"`

I had to type `phyton3` instead of `phyton` and the device name I had to put into quotation marks.

Like that it works fine now and the wave is not annoying fast anymore.

**Comment by Teskann** [comment]
Hi @HeidrHH, my pleasure to share this script with you.

Indeed, you need to use Python 3. If `python` binds to Python 2.x, you might need to call `python3` instead. However, this should not be needed on recent systems.

Indeed, the quotes are required, otherwise the script will parse every white space as a delimiter for arguments separation.

**Comment by Teskann** [comment]
Thank you for your feedback, I added details to the read me so it's more clear.
